name: Build and Deploy MkDocs

on:
  # Allow manual triggers and automatic triggers on specific branches and paths
  workflow_dispatch: # Allows manual execution of the workflow
  push:
    branches:
      - main # Trigger on pushes to the main branch
    paths:
      - 'docs/**' # Trigger when files in the docs folder are modified
      - 'mkdocs.yml' # Trigger when the mkdocs.yml file is modified

permissions:
  contents: read # Required to read repository contents
  pages: write # Required to deploy to GitHub Pages
  id-token: write # Required for authentication with GitHub Pages

concurrency:
  group: 'pages' # Ensures only one workflow runs at a time for this group
  cancel-in-progress: false # Do not cancel in-progress workflows

jobs:
  buildAndDeploy:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    environment:
      name: github-pages # Required environment for GitHub Pages
      url: ${{ steps.deployment.outputs.pages_url }} # URL of the deployed site

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x' # Use the latest Python 3.x version

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: |
          pip install mkdocs-material mkdocstrings-python pillow cairosvg mkdocs-mermaid2-plugin

      # Step 4: Build the documentation
      - name: Build Documentation
        run: mkdocs build # Builds the site into the 'site/' directory

      # Step 5: Configure GitHub Pages
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3
        # Configures the repository for GitHub Pages deployment

      # Step 6: Upload the built site as an artifact
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3 # Changed to upload-pages-artifact
        with:
          path: 'site/' # Upload the 'site/' directory generated by MkDocs

      # Step 7: Deploy the site to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment # Required for environment URL
        uses: actions/deploy-pages@v4
        # Deploys the uploaded artifact to GitHub Pages
