name: Performance Tests

on:
  workflow_dispatch:  # Allow manual trigger
  schedule:
    - cron: '0 0 * * 1'  # Run weekly on Mondays at midnight
  push:
    branches: [ main, master ]
    paths:
      - 'src/**'
      - 'src/test/resources/configs/**'  # Run when test configs change
  pull_request:
    branches: [ main, master ]
    paths:
      - 'src/**'
      - 'src/test/resources/configs/**'

jobs:
  performance-test:
    name: Run Performance Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      
      - name: Clean workspace
        run: |
          rm -rf target || true
          mkdir -p target/surefire-reports
          mkdir -p target/jmeter-reports
      
      - name: Compile code
        run: mvn clean && mvn compile
        
      - name: run tests
        run: |
          mvn test
                
      - name: Archive JMeter Reports and Logs
        uses: actions/upload-artifact@v4
        if: always()  # Archive even if tests fail
        with:
          name: jmeter-reports-and-logs
          path: |
            target/jmeter-reports/
            target/surefire-reports/
          retention-days: 30